[package]
name = "afirmflasher"
version = "0.1.0"
authors = ["Marius Gripsgard <marius@ubports.com>"]

[dependencies]
reqwest = "0.8.6"
serde_json = "1.0.22"
serde_derive = "1.0.69"
serde = "1.0.69"
tar = "0.4.16"
libc = "0.2.42"
sha2 = "0.7.1"
